@domain.verify @extended @req.CAT-FR-GD-01
Feature: JWT Signature Verification
  As a Federated Catalogue API consumer
  I want JWT-wrapped Verifiable Credentials to be cryptographically verified
  So that the catalogue rejects invalid or tampered credentials

  # JWT compact serializations are auto-detected by the server from the body content (starts with "eyJ").
  # The verify endpoint accepts application/json for all credential types; content-based detection applies.
  #
  # Security guards that fire BEFORE DID resolution (config-agnostic, no test DID infrastructure needed):
  #   - alg:none rejection  → ClientException → 400 Bad Request
  #   - missing iss claim   → ClientException → 400 Bad Request
  #   - expired exp claim   → VerificationException → 422 Unprocessable Entity
  #
  # Positive signature tests require @cfg.strict: a did:web DID document with JWT assertion methods
  # served by did-server, and fixtures signed with the corresponding key.
  # See scripts/generate-jwt-fixture.py for fixture generation instructions.

  Background:
    Given CAT Keycloak is up
      And saved Keycloak token
      And Federated Catalogue Server is up

  # --- Security guard tests (config-agnostic: fail before DID resolution) ---

  @smoke
  Scenario: JWT with alg:none is rejected with 400
    # alg:none check fires before DID resolution — ClientException → 400 Bad Request.
    # Inline JWT: header={"alg":"none"}, payload={"iss":"did:web:issuer.example.com"}
    When verify credential
      """
      eyJhbGciOiJub25lIn0.eyJpc3MiOiJkaWQ6d2ViOmlzc3Vlci5leGFtcGxlLmNvbSJ9.
      """
    Then get http 400:Bad Request code

  @smoke
  Scenario: JWT missing iss claim is rejected with 400
    # iss guard fires before DID resolution — ClientException → 400 Bad Request.
    # Inline JWT: alg=EdDSA, payload={"sub":"did:web:example.com"} (no iss), dummy signature.
    When verify credential
      """
      eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6d2ViOmV4YW1wbGUuY29tIn0.ZHVtbXlfc2lnbmF0dXJlX2Zvcl90ZXN0aW5nX29ubHk
      """
    Then get http 400:Bad Request code

  @smoke
  Scenario: JWT with expired exp claim is rejected with 422
    # Loire VC JWT signed with did:web:did-server#jwt-key-1, exp=1000000000 (2001-09-08).
    # exp check fires before DID resolution — VerificationException → 422.
    When verify credential from fixture "vc20/invalid/participant-expired.vc2.jwt"
    Then get http 422:Unprocessable Entity code

  # --- Signature-skip path (@cfg.default) ---

  @smoke @cfg.default
  Scenario: JWT VC verify with signatures disabled returns 200
    # With verifyVCSignature=false and verifyVPSignature=false, the server skips
    # JwtSignatureVerifier — the dummy-signed fixture is accepted.
    When verify credential from fixture "loire/valid/participant.vc2.jwt" skipping signatures
    Then get http 200:Success code

  # --- Positive signature verification (@cfg.strict) ---
  # These scenarios require:
  #   1. did-server running with a JWT assertion method in the DID document
  #   2. Signed JWT fixtures generated by scripts/generate-jwt-fixture.py
  # Run with: ./dev.sh strict && make run_cat_bdd_dev MODE=strict

  @smoke @req.CAT-FR-GD-01 @cfg.strict
  Scenario: JWT VC with valid EdDSA signature verifies successfully
    # Loire VC JWT (typ=vc+jwt) signed with did:web:did-server#jwt-key-1 (Ed25519).
    # gx:LegalPerson credential subject passes semantic validation.
    When verify credential from fixture "loire/valid/participant.vc2.signed.jwt"
    Then get http 200:Success code
    And response has non-empty validatorDids

  @req.CAT-FR-GD-01 @cfg.strict
  Scenario: JWT VP with valid signature and matching iss/holder verifies successfully
    # Loire VP JWT (typ=vp+jwt) where iss == holder == did:web:did-server.
    When verify credential from fixture "loire/valid/participant.vp2.signed.jwt"
    Then get http 200:Success code
    And response has non-empty validatorDids

  @req.CAT-FR-GD-01 @cfg.strict
  Scenario: JWT VP with EnvelopedVerifiableCredential and valid signature verifies successfully
    # Loire VP JWT (typ=vp+jwt) where the inner VC is wrapped as EnvelopedVerifiableCredential
    # with a data:application/vc+jwt URI, signed with did:web:did-server#jwt-key-1 (Ed25519).
    When verify credential from fixture "loire/valid/participant-vp.loire.signed.jwt"
    Then get http 200:Success code
    And response has non-empty validatorDids

  @cfg.strict
  Scenario: JWT with corrupted signature is rejected with 422
    # Loire VC JWT with iss=did:web:did-server (resolves) but a tampered signature.
    When verify credential from fixture "vc20/invalid/bad-signature.vc2.jwt"
    Then get http 422:Unprocessable Entity code

  @cfg.strict
  Scenario: JWT VP with iss not matching holder is rejected with 422
    # Loire VP JWT where iss=did:web:did-server, holder=did:web:other-participant.example.com.
    When verify credential from fixture "vc20/invalid/vp-iss-holder-mismatch.jwt"
    Then get http 422:Unprocessable Entity code
