@domain.asset @req.CAT-FR-GD-01
Feature: Loire Credential Compatibility
  As a Federated Catalogue operator
  I want Loire-format Gaia-X credentials (ICAM 24.07 / W3C VC-JOSE-COSE) to be accepted
  So that the catalogue supports the current Gaia-X standard

  # Loire JWTs differ from VC 2.0 (danubetech path):
  #   - typ: vc+jwt / vp+jwt (W3C VC-JOSE-COSE headers)
  #   - Credential fields are TOP-LEVEL in JWT payload (no "vc"/"vp" wrapper claim)
  #   - Uses 2511 namespace (gx:LegalPerson instead of gax-core:Participant)
  #   - VP uses EnvelopedVerifiableCredential with data: URIs
  #
  # Signed fixtures generated by: scripts/generate-jwt-fixture.py loire-vc / loire-vp
  # Requires did-server with matching public key in assertionMethod.

  Background:
    Given CAT Keycloak is up
      And saved Keycloak token
      And Federated Catalogue Server is up

  @smoke @cfg.default @cfg.strict
  Scenario: Upload a Loire VC with W3C headers
    # Loire VC JWT: typ=vc+jwt, cty=vc, 2511 namespace, gx:LegalPerson type.
    # Tests the full pipeline: FormatDetector → LoireJwtParser → 2511 type resolution → storage.
    Given credential from fixture "loire/valid/participant.loire.signed.jwt" is not uploaded
    When add credential from fixture "loire/valid/participant.loire.signed.jwt" with content-type "application/vc+jwt"
    Then get http 201:Created code

  @cfg.default @cfg.strict
  Scenario: Upload a Loire VP with EnvelopedVerifiableCredential
    # Loire VP JWT: typ=vp+jwt, cty=vp. Inner VC embedded as EnvelopedVerifiableCredential
    # with data:application/vc+jwt,<jwt> URI. Tests VP extraction + inner VC processing.
    Given credential from fixture "loire/valid/participant-vp.loire.signed.jwt" is not uploaded
    When add credential from fixture "loire/valid/participant-vp.loire.signed.jwt" with content-type "application/vp+jwt"
    Then get http 201:Created code
